//
//  FixtureWriter.swift — emits the recorded traces as a generated Swift
//  fixture file for the app's replay tests (`VoiceBargeReplayTests`), which
//  drive the REAL `VoiceEndpointer` + `EchoResidualFloor` over them with the
//  shipped constants. The calibration lock: retune a constant and the field
//  traces tell you what it does.
//

import Foundation

enum FixtureWriter {

    static func write(traces: [String: [Float]], to path: String) throws {
        let ordered = traces.sorted { $0.key < $1.key }
        var out = """
            //
            //  VoiceLabFixtures.swift
            //  tesseractTests
            //
            //  GENERATED by tools/voice-hold-lab (--emit-fixture) — do not edit.
            //  20 Hz mic levels in the app meter's domain (RMS → (dB+60)/60),
            //  recorded on real hardware through a VPIO capture engine. Consumed
            //  by VoiceBargeReplayTests; regenerate after hardware or constant
            //  changes: see tools/voice-hold-lab/RUNBOOK.md.
            //

            import Foundation

            enum VoiceLabFixtures {

            """
        for (name, levels) in ordered {
            let values = levels.map { String(format: "%.4f", $0) }
                .joined(separator: ", ")
            out += "    static let \(name): [Float] = [\(values)]\n\n"
        }
        out += "}\n"
        try out.write(toFile: path, atomically: true, encoding: .utf8)
        print("fixtures → \(path)  (\(ordered.map(\.key).joined(separator: ", ")))")
    }
}
